### PR TITLE
Major refactoring and reorganization

### LINKED ISSUE #36: Major refactoring and reorganization needed.
The code base has become very cluttered and messy.
# planned fixes

- rewrite the whole error/warning system, give every type of error/warning its own class
- convert internal errors (such as `errorCompilerBug`) into exceptions, use a custom class
- declutter **_parser.cxx_**, potentially break up the `parse` function
- remove misc functions from **_parser.cxx_**
- change errors inside `resolve` to throw exceptions rather than returning nullptr

### PR DESCRIPTION
**Pull request by DefinitelyNotAGirl**
PR for #36

### CODE REVIEW

File: src/resolve.cxx [hunk 1]
```diff
@@ -731,6 +697,85 @@ void makeNewToken(std::string& working, uint64_t i, std::vector<token>& tokens,t
 
     working = "";
 }
+
+static void resolve_I(variable*& left, token& __leftHand, token& t)
```
Comment (DefinitelyNotAGirl) [inline src/resolve.cxx:701]: this resolve_I/resolve_II situation sucks but im not sure what else to do about it, so it's staying for now

File: src/resolve.cxx [hunk 2]
```diff
@@ -731,6 +697,85 @@ void makeNewToken(std::string& working, uint64_t i, std::vector<token>& tokens,t
...
+        	    left = call(indexOP,args__);
+        	}
+		}
+		catch(noSuchVariable e){}
+		catch(noSuchFunction e){}
+    }
+    if(left == nullptr)
+		noSuchIdentifier("",originCoreHere,source(),__leftHand.text);
+}
 /**
```
Comment (DefinitelyNotAGirl) [inline src/resolve.cxx]: this situation sucks, not sure what to do about it tho, so it's staying for now

**Comment by DefinitelyNotAGirl** [comment]
# Conclusion

- Swapped out pretty much all error logic, remaining cases of old logic are to be switched whenever encountered
- completely reworked resolve.cxx, removed resolveIMM
- added new stack trace logic, although it seems to be having some spooky issues

# Issues
- #38
